name: arogya_2_0
description: "Offline-first healthcare app for ASHA/Anganwadi workers"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0

  sqflite: ^2.3.3
  path_provider: ^2.1.2

  flutter_localizations:
    sdk: flutter

  url_launcher: ^6.3.0

  fl_chart: ^0.68.0
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
