name: arogya_2_0
description: "Offline-first healthcare app for ASHA/Anganwadi workers"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0

  sqflite: ^2.3.3
  path_provider: ^2.1.2
  path: ^1.9.0

  flutter_localizations:
    sdk: flutter

  url_launcher: ^6.3.0

  fl_chart: ^1.2.0
  google_maps_flutter: ^2.16.0
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.5
  telephony:
    path: plugins/telephony
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true