// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVKiG39xtZtGv_fGYOumPABE4sU19e21Y',
    appId: '1:539289038349:web:c787528a892b4ec0672f44',
    messagingSenderId: '539289038349',
    projectId: 'arogya-4a6be',
    authDomain: 'arogya-4a6be.firebaseapp.com',
    storageBucket: 'arogya-4a6be.firebasestorage.app',
    measurementId: 'G-T8K71CE7G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBL3tn7_x2b5n9uhJgrxNXm7YC1ArPuVI',
    appId: '1:539289038349:android:9fb1a99d51c189dc672f44',
    messagingSenderId: '539289038349',
    projectId: 'arogya-4a6be',
    storageBucket: 'arogya-4a6be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Gug6uAIDQENcp_sl71-0HsgBe6az1_c',
    appId: '1:539289038349:ios:c6e8e5d808a8b203672f44',
    messagingSenderId: '539289038349',
    projectId: 'arogya-4a6be',
    storageBucket: 'arogya-4a6be.firebasestorage.app',
    iosBundleId: 'com.example.arogya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Gug6uAIDQENcp_sl71-0HsgBe6az1_c',
    appId: '1:539289038349:ios:c6e8e5d808a8b203672f44',
    messagingSenderId: '539289038349',
    projectId: 'arogya-4a6be',
    storageBucket: 'arogya-4a6be.firebasestorage.app',
    iosBundleId: 'com.example.arogya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVKiG39xtZtGv_fGYOumPABE4sU19e21Y',
    appId: '1:539289038349:web:d5040b5fbf43357e672f44',
    messagingSenderId: '539289038349',
    projectId: 'arogya-4a6be',
    authDomain: 'arogya-4a6be.firebaseapp.com',
    storageBucket: 'arogya-4a6be.firebasestorage.app',
    measurementId: 'G-J5B0NP00ZM',
  );
}
